services:
  # Service cho người dùng
  user_service:
    build: ./user_service  # <-- Đảm bảo đường dẫn đúng
    ports:
      - "8000:8000"
    volumes:
      - ./user_service:/app

  # Service cho lịch hẹn
  appointment_service:
    build: ./appointment_service # <-- Đảm bảo đường dẫn đúng
    ports:
      - "8001:8001"
    volumes:
      - ./appointment_service:/app
    depends_on:
      - user_service

  # Service cho dữ liệu lâm sàng
  clinical_service:
    build: ./clinical_service # <-- Đảm bảo đường dẫn đúng
    ports:
      - "8002:8002"
    volumes:
      - ./clinical_service:/app
    depends_on:
      - user_service

  # Service cho Chatbot AI (Flask)
  web_portal: # <-- ĐỔI TÊN Ở ĐÂY
    build: ./ChatbotForHealthcare
    ports:
      - "5000:5000"
    volumes:
      - ./ChatbotForHealthcare:/app
    # Thêm depends_on để đảm bảo các service backend khởi động trước (tùy chọn nhưng nên có)
    depends_on:
      - user_service
      - appointment_service
      - clinical_service

networks:
  default:
    driver: bridge