# Generated by Django 5.2 on 2025-05-06 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_id', models.IntegerField(db_index=True, help_text='ID of the Appointment from the Appointment Service', unique=True, verbose_name='appointment id')),
                ('patient_id', models.IntegerField(db_index=True, help_text='ID of the Patient', verbose_name='patient id')),
                ('doctor_id', models.IntegerField(db_index=True, help_text='ID of the Doctor', verbose_name='doctor id')),
                ('diagnosis_code', models.CharField(blank=True, db_index=True, help_text='ICD code, e.g., J06.9', max_length=50, null=True, verbose_name='diagnosis code')),
                ('description', models.TextField(help_text='Detailed diagnosis description and clinical notes.', verbose_name='description')),
                ('diagnosis_time', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the diagnosis was recorded.', verbose_name='diagnosis time')),
            ],
            options={
                'verbose_name': 'diagnosis',
                'verbose_name_plural': 'diagnoses',
                'ordering': ['-diagnosis_time'],
            },
        ),
        migrations.CreateModel(
            name='LabOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_id', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='appointment id')),
                ('patient_id', models.IntegerField(db_index=True, verbose_name='patient id')),
                ('doctor_id', models.IntegerField(db_index=True, verbose_name='doctor id')),
                ('test_name', models.CharField(max_length=255, verbose_name='test name')),
                ('order_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='order time')),
                ('status', models.CharField(choices=[('Ordered', 'Ordered'), ('Received', 'Received'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], db_index=True, default='Ordered', max_length=20, verbose_name='status')),
                ('notes', models.TextField(blank=True, help_text='Additional notes for the lab technician.', null=True, verbose_name='notes')),
                ('diagnosis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_orders', to='clinical.diagnosis', verbose_name='diagnosis')),
            ],
            options={
                'verbose_name': 'lab order',
                'verbose_name_plural': 'lab orders',
                'ordering': ['-order_time'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_date', models.DateField(auto_now_add=True, db_index=True, verbose_name='prescription date')),
                ('notes', models.TextField(blank=True, help_text='Additional notes for the prescription or pharmacist.', null=True, verbose_name='notes')),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='clinical.diagnosis', verbose_name='diagnosis')),
            ],
            options={
                'verbose_name': 'prescription',
                'verbose_name_plural': 'prescriptions',
                'ordering': ['-prescription_date'],
            },
        ),
        migrations.CreateModel(
            name='PrescribedMedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=255, verbose_name='medication name')),
                ('dosage', models.CharField(help_text="e.g., '500mg', '1 tablet'", max_length=100, verbose_name='dosage')),
                ('frequency', models.CharField(help_text="e.g., 'Twice a day', 'Every 6 hours'", max_length=100, verbose_name='frequency')),
                ('duration', models.CharField(help_text="e.g., '7 days', 'Until finished'", max_length=100, verbose_name='duration')),
                ('instructions', models.TextField(blank=True, help_text='Specific instructions for the patient.', null=True, verbose_name='instructions')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='clinical.prescription', verbose_name='prescription')),
            ],
            options={
                'verbose_name': 'prescribed medication',
                'verbose_name_plural': 'prescribed medications',
            },
        ),
    ]
